CREATE TABLE `USER_INFO` (
  `INFO_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户信息ID',
  `USER_NAME` varchar(50) DEFAULT NULL COMMENT '用户真实姓名',
  `USER_AGE` int(11) DEFAULT NULL COMMENT '用户年龄',
  `USER_GANDER` int(4) DEFAULT NULL COMMENT '用户性别 0 未知 1 男 2 女',
  `USER_ADDRESS` varchar(200) DEFAULT NULL COMMENT '用户居住地址',
  `USER_QQ` varchar(20) DEFAULT NULL COMMENT '用户QQ号',
  `USER_WECHAT` varchar(20) DEFAULT NULL COMMENT '用户微信号',
  `USER_MOBILE` varchar(20) DEFAULT NULL COMMENT '用户手机',
  PRIMARY KEY (`INFO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='用户信息表';